FROM golang:1.23 AS base

WORKDIR /viswals

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

COPY .env .

RUN CGO_ENABLED=0 go build ./cmd/producer-service/ 

FROM scratch

COPY --from=base /viswals/producer-service /
COPY --from=base /viswals/.env /
COPY --from=base /viswals/csvs/demo.csv /
COPY --from=base /viswals/csvs/users.csv /

CMD ["/producer-service"]
